### ISSUE TITLE
CATP11

### ISSUE THREAD

**Issue by NicolasCendron** [schnorr/mlp#11]
1)Implementa em C++ um tipo de dados Fila que trabalhe com qualquer tipo.
Use templates.
Com tal definição, implemente uma pilha de pilha de pilha de inteiros.

É uma FILA ou uma PILHA?

é um erro de enunciado ou realmente é uma classe FILA que internamente é uma Pilha?

**Comment by schnorr** [comment]
É uma FILA mesmo. Corrigido em c662189.  Obrigado por relatar.
