### ISSUE TITLE
Como arrumar acentuação no latex?

### ISSUE THREAD

**Issue by augustotimm** [schnorr/mlp#19]
Não estou conseguindo arrumar a o acento que está na nota do final da página, nem achar onde esse trecho de texto se encontra no modelo
![700be6db-9c77-43dd-9a39-248f8018546a]
(https://user-images.githubusercontent.com/11176059/45749837-569e8600-bbe3-11e8-8d3d-a1c935fec18e.png)

**Comment by btrevizan** [comment]
Tenta colocar `\usepackage[utf8]{inputenc}` no início do arquivo.

**Comment by augustotimm** [comment]
> Tenta colocar `\usepackage[utf8]{inputenc}` no início do arquivo.

Já possui, eu copiei o modelo do professor e já tem esse package. O estranho é que é apenas nesse trecho que acontece esse problema da acentuação.

**Comment by btrevizan** [comment]
> Já possui, eu copiei o modelo do professor e já tem esse package. O estranho é que é apenas nesse trecho que acontece esse problema da acentuação.

Tu copiou o texto de algum outro lugar? Se sim, apaga e tenta escrever. Às vezes, em alguns PDFs, as acentuações possuem uma codificação que o Latex não sabe interpretar.

**Comment by augustotimm** [comment]
Conversado com o professor após a aula e o erro foi corrigido, bastou usar o usepackage como o trevizan falou, mas no arquivo rel_mlp.def.

**Comment by schnorr** [comment]
Obrigado pela confirmação da correção.

O commit no repositório `mlpreport` [mostra a alteração realizada](https://github.com/schnorr/mlpreport/commit/c1935a680ee932361b95b4fa281118fa8040a567).
