### ISSUE TITLE
Não é possível fazer o make

### ISSUE THREAD

**Issue by cvrnogueira** [schnorr/mlp#2]
Ao entrar no diretório de conteúdos e fazer o make para gerar o pdf ocorrem diferentes erros(até agora sempre para na pasta exceções)

Trecho dos erros que obtive:

> emacs -batch implementacao.org --funcall org-babel-tangle
> Symbol's function definition is void: org-babel-tangle
> make[1]: * [implementacao.pdf] Error 255
> make: * [all] Error 2

> 
> ``Wrote /home/aluno/Downloads/mlp-master/conteudo/aulas/excecoes/implementacao.tex
> Processing LaTeX file ./implementacao.tex...
> (Shell command failed with error)
> Searching for program: is a directory, 
> ../../Makefile.base:2: recipe for target 'implementacao.pdf' failed
> make[1]: *** [implementacao.pdf] Error 255
> make[1]: Leaving directory '/home/aluno/Downloads/mlp-master/conteudo/aulas/excecoes'
> Makefile:2: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by schnorr** [comment]
Olá @cvrnogueira, refiz o comando aqui (no diretório `conteudo/aulas/excecoes`) e os slides PDF foram compilados normalmente. Olhando novamente para a saída com o erro que tu nos passaste, temos:
```
emacs -batch implementacao.org --funcall org-babel-tangle
Symbol's function definition is void: org-babel-tangle
```
Indicando que a função `org-babel-tangle` não está definida. Isso quer dizer que o ORG não está instalado. Chegaste a instalá-lo? Se sim, qual a versão dele? Qual a versão do teu emacs?

**Comment by cvrnogueira** [comment]
Olha, professor, eu tinha instalado sim, maas como resolvi meu problema, na verdade, foi respondendo "no" pra pergunta que antes eu respondia que sim:

> "Evaluate this R code block (lucas) on your system? (yes or no)" ,

 e dai gerou os pdf's bem certinho e não deu mais erro. Não sei o porque, uma vez que tenho R no Pc e tal. 
Mas enfim, resolvido! Obrigada!! :100: :1st_place_medal:

**Comment by schnorr** [comment]
Ok, se o problema desapareceu, fechamos #2,
