### ISSUE TITLE
CATP #10.B

### ISSUE THREAD

**Issue by LucasAlegre** [schnorr/mlp#28]
Olá,

Seria legal disponibilizar a correção do catp 10, já que a maior nota  da turma foi por volta de 4.
Lembro que para pós-fixada conferi minhas respostas com esse site:
http://scanftree.com/Data_Structure/prefix-postfix-infix-online-converter

Abraços,
Lucas

**Comment by schnorr** [comment]
Olá @LucasAlegre, acabo de conversar com um colega da turma e identificamos um erro no cálculo da nota final dos catps três e dez, que agora foram corrigidos. Esta correção está integrada no commit  94fac75. Vou mesmo assim providenciar a correção.

**Comment by schnorr** [comment]
Veja a resolução do catp 10.B no commit c494a210f465c2af8c9c9643a5cc206202f85380, ou [diretamente no arquivo](https://github.com/schnorr/mlp/blob/master/catps/resp/10.B.org).
