### ISSUE TITLE
Dúvida capt2

### ISSUE THREAD

**Issue by lauracorssac** [schnorr/mlp#3]
Olá!
Fiquei com uma dúvida na especificação do catp2.
Está escrito nos exercícios que o programa deve retornar uma lista, mas, os exemplos de saída estão no formato " [1] 1 2 3 ", que foi dito que não é realmente uma lista. Queria saber se é nesse formato mesmo ou no formato que a função list(1,2,3) retorna: 
[[1]]
[1] 1
[[2]]
[1] 2
[[3]]
[1] 3
Obrigada!
Laura

**Comment by schnorr** [comment]
Olá @lauracorssac, pode ser tanto uma lista ou um vetor.
