### ISSUE TITLE
É possivel receber as perguntas  de mlp da P1 e P2 para estudos para recuperação?

### ISSUE THREAD

**Issue by mariojose123** [schnorr/mlp#35]

**Comment by schnorr** [comment]
Prezado @mariojose123, agradeço se puderes tratar desse tipo de questionamento por e-mail. Acredito ser mais adequado. Quanto a disponibilização das perguntas das provas P1 e P2, entendo que os alunos tem acesso a um extenso [conjunto da CATPs já resolvidos](https://github.com/schnorr/mlp/tree/master/catps) para a maior parte das questões propostas. Eventuais questões que não são abordadas pelos CATPs tem seu conteúdo abordado ou em [nossa bibliografia](https://github.com/schnorr/mlp#bibliografia) (especialmente Sebesta e Scott, conforme [mapeamento disponível no nosso conteúdo](https://github.com/schnorr/mlp/tree/master/conteudo), ou nos slides que foram preparados e utilizados ao longo do semestre, [também disponíveis](https://github.com/schnorr/mlp/tree/master/conteudo). As provas antigas P1, P2 e PR podem ser encontradas no [histórico do arquivo acompanhamento.org](https://github.com/schnorr/mlp/commits/master/acompanhamento.org), veja por exemplo o estado [no final do semestre 2018/1](https://github.com/schnorr/mlp/blob/ae22b8cbfa47c8600a059c6dd7ccebddf06404cb/acompanhamento.org), com um detalhamento de quais tipos de questões foram propostas e as suas respostas esperadas.
