### ISSUE TITLE
CATP #10

### ISSUE THREAD

**Issue by Robuske** [schnorr/mlp#7]
Professor, acredito que a questão 3 esteja com erros no meio da expressão a ser avaliada, tem uns "\" perdidos no meio.

Outra coisa, na questão 2, a transformação tem que ter exatamente a mesma ordem de operações ou só o mesmo resultado? Por exemplo, posso mudar a ordem que as multiplicações vão ocorrer e coisas assim

**Comment by schnorr** [comment]
Obrigado por avisar; a expressão préfixada da Q3 já foi corrigida com o commit e5903e8. Na Q2, sim, tem que ter exatamente a mesma ordem de operações.
